### ISSUE TITLE
Code blocks don't follow site width

### ISSUE THREAD

**Issue by TheMatten** [srid/zulip-archive#8]
This is mostly visible on phones:
![IMG_20200202_083925](https://user-images.githubusercontent.com/21198836/73604972-87911800-4598-11ea-86d4-97b41d72fb89.jpg)
We probably want them to be shown in smaller, scrollable frame, similarly to Zulip itself.

**Comment by roryokane** [comment]
I haven’t tested, but I think the following two CSS rules would achieve this:

~~~css
.select-the-code-blocks-somehow {
  overflow: auto;
  max-width: 100%;
}
~~~

I see that `Main.hs` currently has [custom CSS for all `code, pre, tt`](https://github.com/srid/zulip-archive/blob/a13e3beac16716c63ae7fd36e182619d69bdc9c8/src/Main.hs#L248). The styles for standalone code blocks should be added next to that section. Note that `code, pre, tt` cannot be the right selector to use because `tt` elements are inline elements, not block elements.

**Comment by srid** [comment]
Awesome @roryokane, that did the trick! 

(Tested using Chrome dev tools; re-open if not actually fixed)
